### PR TITLE
update: packages and fix vulnerabilities

### LINKED ISSUE #15: Update `@angular-devkit` and `@schematics` to v13
The upgrade from Angular DevKit to v12 to v13 included some breaking changes, notably around the JSON parser. They have removed the public API that we use in `json-utils.ts`. List of public APIs they had removed

```
- JsonAstNode
- JsonAstKeyValue
- JsonAstObject
- JsonParseMode
- parseJsonAst
```

They recommend using a separate JSON parser [jsonc-parser](https://www.npmjs.com/package/jsonc-parser)

Related PR: https://github.com/nightwatchjs/nightwatch-schematics/pull/14, https://github.com/angular/angular-cli/pull/21563

### PR DESCRIPTION
**Pull request by vaibhavsingh97**

### CODE REVIEW

**Comment by trazek** [comment]
Any update on this PR? @vaibhavsingh97

**Comment by trazek** [comment]
Any chance this can be updated to use a newer version of the `@angular-devkit` packages?

**Comment by swrdfish** [comment]
Looking into it.

**Comment by vaibhavsingh97** [comment]
@trazek we have released a new version https://www.npmjs.com/package/@nightwatch/schematics/v/1.0.0

**Pull request merged**
